const data = {
    "skills": [
        { "name": "Arcana", "description": "Knowledge of magic and spells." },
        { "name": "History", "description": "Knowledge of historical events and lore." },
        { "name": "Perception", "description": "Ability to notice details and sense changes in the environment." },
        { "name": "Stealth", "description": "Ability to move silently and hide from detection." },
        { "name": "Athletics", "description": "Physical prowess in climbing, jumping, and other physical activities." },
        { "name": "Deception", "description": "Ability to lie and trick others convincingly." },
        { "name": "Speech", "description": "Ability to sweet talk your way out of sticky situations." },
        { "name": "Longbow Proficiency", "description": "Proficient with a Longbow" },
        { "name": "Shortbow Proficiency", "description": "Proficient with a Shortbow" },
        { "name": "Dagger Proficiency", "description": "Proficient with a Dagger" },
        { "name": "Longsword Proficiency", "description": "Proficient with a Longsword" },
        { "name": "Sword Proficiency", "description": "Proficient with a Sword" },
        { "name": "Seafaring Proficiency", "description": "Proficient with Seafaring" },
        { "name": "Heavy Armour Proficiency", "description": "Proficient with Heavy Armour" },
        { "name": "Polearm Proficiency", "description": "Proficient with a Polearm" },
        { "name": "Crossbow Proficiency", "description": "Proficient with a Crossbow" },
        { "name": "Horse Proficiency", "description": "Proficient with a Horse" },
        { "name": "Medium Armour Proficiency", "description": "Proficient with Medium Armour" },
        { "name": "Light Armour Proficiency", "description": "Proficient with Medium Armour" },
        { "name": "Enchanted Armour Proficiency", "description": "Proficient with Enchanted Armour" },
        { "name": "Two-Handed Weapon Proficiency", "description": "Proficient with Two-Handed Weapon" },
        { "name": "Sling Proficiency", "description": "Proficient with a Sling" },
        { "name": "Medicine", "description": "Proficiency with medicine and remedies" },
        { "name": "Intimidation", "description": "Ability to frighten and coerce others." }
    ],
    "senses": [
        { "name": "Blindsight", "description": "Ability to perceive surroundings without sight, within a specific range." },
        { "name": "Tremorsense", "description": "Ability to sense vibrations in the ground to detect nearby creatures." },
        { "name": "Truesight", "description": "Ability to see things as they actually are, within a specific range." },
        { "name": "Passive Perception", "description": "Natural awareness of surroundings without actively looking." },
        { "name": "Cleric Intuition", "description": "Natural awareness of what is causing ailments" },
        { "name": "Darkvision", "description": "Ability to see in the dark within a specific range." }
    ],
    "languages": [
        { "name": "Laurentian", "description": "The language spoken by Imperial and Thalassar Humans." },
        { "name": "Alvirran", "description": "The language spoken by the Dominion." },
        { "name": "Tenebraen", "description": "The language of the Tenebrae." },
        { "name": "Gua'Liconian", "description": "The language of the Gua'licon." },
        { "name": "Any two languages", "description": "Any two languages used in the area the character is from." },
        { "name": "Dredic", "description": "The language of the Witch King of the East." },
        { "name": "The Voice", "description": "Cast your voice to the ears of others up to 120ft away." },
        { "name": "None", "description": "Does not speak any languages." },
        { "name": "Any one language", "description": "Usually the language spoken where they are from." }
    ],
    "resistances": [
        { "name": "Fire", "description": "Resistant to fire damage." },
        { "name": "Cold", "description": "Resistant to cold damage." },
        { "name": "Lightning", "description": "Resistant to lightning damage." },
        { "name": "Necrotic", "description": "Resistant to necrotic damage." },
        { "name": "Bludgeoning, Piercing, and Slashing", "description": "Resistant to damage from nonmagical weapons." }
    ],
    "magicResistance": [
        { "name": "Advantage on saving throws against spells", "description": "Has advantage on saving throws against spells and other magical effects." },
        { "name": "Resistance to spell damage", "description": "Takes half damage from spells." }
    ],
    "spellcasting": [
        { "name": "Aqua Shot", "description": "Shoots a concentrated jet of water from the fingertips, capable of exerting force enough to push objects or stagger opponents, dealing 1d6 + INT mod bludgeoning damage." },
        { "name": "Arcane Battery", "description": "Create a small, portable power source that can provide energy to a gadget or minor magical device for a short period." },
        { "name": "Army of the Damned", "description": "Conjures a horde of undead creatures from the surrounding area, including powerful wraiths and zombies, to overwhelm enemies. Each undead creature deals 3d6 + INT mod necrotic damage." },
        { "name": "Abyssal Deluge", "description": "Unleashes an overwhelming deluge of pressurized water from the sky, capable of flattening structures and sweeping away armies, dealing 5d10 + INT mod bludgeoning damage." },
        { "name": "Battle Frenzy", "description": "Enter a state of heightened combat ability, increasing attacks by +1 and damage by +2." },
        { "name": "Battlefield Dominance", "description": "Unleash a series of attacks that strike multiple enemies in quick succession, dealing significant area-of-effect damage. Each attack deals 2d6 + STR mod damage." },
        { "name": "Blinding Gaze", "description": "The creature targets one creature it can see within range, potentially blinding it." },
        { "name": "Briar Wall", "description": "Causes thorny bushes or undergrowth to rapidly grow into a dense, prickly barrier, dealing 1d8 + INT mod piercing damage to anyone who tries to pass through." },
        { "name": "Cinder Storm", "description": "Conjures a hail of burning cinders over a wide area, causing 1d4 + INT mod fire damage to multiple targets, with potential for chaos among enemy ranks." },
        { "name": "Corpse Puppeteer", "description": "Grants the ability to animate and control a dead body for a short period, using it to perform tasks or fight. The animated corpse deals 1d6 + INT mod bludgeoning damage." },
        { "name": "Counterspell", "description": "Interrupts the casting of a spell." },
        { "name": "Death Fog", "description": "Releases a creeping fog that induces severe fear, hallucinations, and cold damage to those caught within it, embodying the terror of the grave. Deals 2d10 + INT mod cold damage." },
        { "name": "Death's Embrace", "description": "A protective cloak of darkness that slightly heals the necromancer while causing unease and minor harm to those who come too close. Heals 1d6 + INT mod hit points per turn and deals 1d4 + INT mod necrotic damage to nearby enemies." },
        { "name": "Decisive Strike", "description": "A devastating attack that deals massive damage and has a high chance of causing critical effects like bleeding or stunning. Deals 3d10 + STR mod damage." },
        { "name": "Dragon's Wrath", "description": "Calls forth the spectral image of a dragon made of fire that sweeps over the battlefield, breathing 4d6 + STR mod fire damage upon all enemies it encounters." },
        { "name": "Echoing Cry", "description": "Amplifies the caster's voice to create an echoing shout that can stun or disorient opponents, dealing 1d8 + INT mod thunder damage." },
        { "name": "Ember Toss", "description": "Casts a small, quick burst of fire from the fingertips, dealing 1d4 + INT mod fire damage to targets or igniting flammable materials." },
        { "name": "Eclipse of Andrew", "description": "Invokes the essence of Andrew the Shadow King to blanket a large area in supernatural darkness, enhancing all necrotic spells and weakening all forms of light and life within it. All necrotic spells deal an additional 1d10 + INT mod necrotic damage." },
        { "name": "Explosive Traps", "description": "Set up traps that cause damage to enemies, useful for defending your campsite or setting ambushes. Deals 2d6 + INT mod explosive damage." },
        { "name": "Fire Bolt", "description": "A spell that hurls a mote of fire at a creature or object within range." },
        { "name": "Fire Cloak", "description": "Wraps the caster in flames that do not harm them but deal 1d6 + STR mod fire damage per turn to any who come too close, offering protection and a melee deterrent." },
        { "name": "Fire Jet", "description": "Emits a continuous stream of fire from the hands, dealing 1d8 + INT mod fire damage per round, usable to cut through obstacles or as a weapon in battle." },
        { "name": "Firebind", "description": "Encircles a target with a ring of fire, immobilizing them and dealing 1d6 + STR mod fire damage per round if they attempt to cross the flame barrier." },
        { "name": "Fireball", "description": "A spell that creates a burst of fire, dealing damage to creatures within range." },
        { "name": "Fissure Call", "description": "Creates a deep fissure in the earth, which can trap large creatures or block pathways, dealing 2d10 + INT mod bludgeoning damage." },
        { "name": "Flashbang", "description": "Deploy a flashbang to disorient enemies, giving you and your party a chance to escape or gain the upper hand in combat. Deals 1d8 + INT mod flash damage and causes disorientation." },
        { "name": "Fog Cloud", "description": "Generates a dense cloud of fog that envelops an area, obscuring sight and cooling the air." },
        { "name": "Galactic Wind", "description": "Unleashes a powerful blast of cosmic energy that sweeps across a wide area, capable of knocking back and stunning enemies. Deals 2d8 + INT mod force damage." },
        { "name": "Ghastly Touch", "description": "A chilling touch that causes minor necrotic damage to living tissue, useful for weakening an opponent or decaying organic matter. Deals 1d4 + INT mod necrotic damage." },
        { "name": "Grave Call", "description": "Summons skeletal warriors from the ground, each armed with necrotic energy and bound to obey the necromancer’s commands. Each skeletal warrior deals 1d8 + INT mod necrotic damage." },
        { "name": "Grove Sentinel", "description": "Animates a tree to serve as a temporary guardian, giving it limited movement and the ability to attack intruders, dealing 2d6 + INT mod bludgeoning damage." },
        { "name": "Gust Wall", "description": "Summons a strong wall of wind that can push back enemies, clear debris, or redirect small bodies of water, dealing 1d6 + INT mod bludgeoning damage." },
        { "name": "Healing Touch", "description": "The creature touches another creature, healing it and removing certain conditions." },
        { "name": "Hellfire Vortex", "description": "Summons a massive swirling storm of fire engulfing a large area, dealing 4d10 + STR mod fire damage to nearly everything in its path." },
        { "name": "Ice Spike", "description": "Freezes water in the air to create sharp spikes of ice that can be hurled at targets or used to create barriers, dealing 1d8 + INT mod piercing damage." },
        { "name": "Inferno Blast", "description": "A powerful explosion of fire centered on a target area, causing 2d10 + STR mod fire damage to anyone caught in the blast radius." },
        { "name": "Innate Spellcasting", "description": "The creature's spellcasting ability is Charisma. It can cast spells innately without material components." },
        { "name": "Island Birth", "description": "Raises a landmass from beneath a body of water, creating a new island and dealing 4d10 + INT mod bludgeoning damage to sea creatures or structures in the area." },
        { "name": "Life Drain", "description": "Siphons vitality from a target to heal the necromancer or strengthen their spells, weakening the victim in the process. Deals 2d6 + INT mod necrotic damage and heals the necromancer for the same amount." },
        { "name": "Magic Missile", "description": "A spell that creates darts of magical force that hit automatically." },
        { "name": "Mage Hand", "description": "A spectral, floating hand appears at a point you choose within range." },
        { "name": "Maelstrom Creation", "description": "Creates a gigantic whirlpool in a large body of water, capable of sinking ships and pulling entire marine forces into the abyss, dealing 4d8 + INT mod bludgeoning damage." },
        { "name": "Meteor Shower", "description": "Calls down a shower of meteorites over a wide area, causing massive destruction and altering the landscape. Deals 4d10 + INT mod bludgeoning damage." },
        { "name": "Meteor Strike", "description": "Summons a small meteor from the sky to strike a targeted area, causing 2d10 + INT mod bludgeoning damage." },
        { "name": "Mirror Image", "description": "Creates illusory duplicates of yourself to confuse attackers." },
        { "name": "Mountain Rise", "description": "Raises a new mountain peak from deep within the earth, dramatically altering the landscape and causing 3d10 + INT mod bludgeoning damage to anything in the affected area." },
        { "name": "Poisoned Strike", "description": "Coat your weapons with poison, dealing additional damage over time to your enemies. Deals 1d6 + DEX mod poison damage per round for 3 rounds." },
        { "name": "Precision Strike", "description": "A powerful attack that targets a specific weak point, dealing critical damage and potentially disabling the enemy. Deals 2d8 + STR mod damage." },
        { "name": "Prestidigitation", "description": "A minor magical trick that novice spellcasters use for practice." },
        { "name": "Reality Bender", "description": "Create devices that can manipulate the fabric of reality, such as time-stopping watches, gravity-inverting boots, or dimension-hopping portals." },
        { "name": "Sand Shift", "description": "Controls sand in a larger area, allowing the mage to reshape sand dunes, create sandstorms, or quicksand traps. Sandstorms cause 1d4 + INT mod slashing damage per round." },
        { "name": "Searing Burst", "description": "The creature emits magical, divine energy, damaging creatures within a radius." },
        { "name": "Shield", "description": "An invisible barrier of magical force appears and protects you." },
        { "name": "Shocking Grasp", "description": "A spell that delivers a jolt of electricity through a touch." },
        { "name": "Solar Flare", "description": "Unleashes a devastating burst of heat and light similar to a small sun, dealing 3d8 + INT mod fire damage and blinding enemies while dispelling darkness-based magic." },
        { "name": "Soul Harvest", "description": "The ultimate necromantic spell that rips the soul from a body, resulting in instant death to the target and a significant power boost to the necromancer. Instantly kills the target and grants the necromancer 4d12 + INT mod temporary hit points." },
        { "name": "Spark Ignite", "description": "A basic spell that allows the mage to ignite small flames on torches or kindling. Perfect for lighting a fire without the need for physical tools. No damage." },
        { "name": "Spectral Chains", "description": "Binds a target with chains formed from condensed shadow, paralyzing them and slowly draining their life force. Deals 2d8 + INT mod necrotic damage per turn." },
        { "name": "Starburst Flare", "description": "Casts a brilliant burst of light that disorients enemies and illuminates dark areas, mimicking the sudden flare of a distant star. Deals 1d6 + INT mod radiant damage." },
        { "name": "Stardust Rebirth", "description": "Uses the cosmic energy of stardust to completely regenerate the caster or an ally, healing all wounds and curing ailments, symbolizing a rebirth akin to that of a dying star. Heals 4d12 + INT mod hit points." },
        { "name": "Tempest Call", "description": "Conjures a localized storm around the caster, complete with strong winds and thunder, dealing 2d6 + INT mod thunder damage to nearby enemies." },
        { "name": "Teleport Spell", "description": "The creature magically teleports, along with any equipment it is wearing or carrying, to an unoccupied space it can see." },
        { "name": "Terrain Mastery", "description": "Manipulate the terrain temporarily to create bridges, clear obstacles, or stabilize loose ground." },
        { "name": "Tremor Track", "description": "Sends a low-intensity seismic wave through the ground that can detect movements or create small tremors to destabilize opponents, dealing 1d6 + INT mod bludgeoning damage." },
        { "name": "Tsunami Summon", "description": "Conjures a massive tsunami that sweeps over coastlines and floods cities, causing massive water damage and reshaping landscapes, dealing 4d10 + INT mod bludgeoning damage." },
        { "name": "Ultimate Enchantments", "description": "Can imbue items with the most powerful magical properties (e.g., +3 to attack or defense, multiple elemental effects, powerful auras) using the rarest materials." },
        { "name": "Vortex Trap", "description": "Conjures a spinning vortex of water on a body of water, capable of trapping and drowning those who enter it, dealing 2d10 + INT mod bludgeoning damage." },
        { "name": "Wall of Flame", "description": "Creates a large, impenetrable wall of fire that blocks enemy advances or traps them, dealing 2d6 + INT mod fire damage to those who touch it." },
        { "name": "Water Whip", "description": "Creates a small whip made of water that can be used to grab objects at a short distance or deliver a wet slap to deter small creatures or foes, dealing 1d4 + INT mod bludgeoning damage." },
        { "name": "Waterform Shield", "description": "Creates a large, protective barrier of swirling water around the caster, which can absorb and dissipate energy from magical and physical attacks." },
        { "name": "Wind Surge", "description": "Creates a powerful blast of air capable of knocking down doors or clearing a large area of enemies and obstacles, dealing 2d8 + INT mod bludgeoning damage." }        
    ],
    "actions": [
        { "name": "Air Lens", "description": "Manipulates air density to create invisible lenses in the air, enhancing or distorting visibility through them." },
        { "name": "Angelic Weapons", "description": "The creature's weapon attacks are magical and deal extra radiant damage." },
        { "name": "Arcane Battery", "description": "Create a small, portable power source that can provide energy to a gadget or minor magical device for a short period." },
        { "name": "Astral Echoes", "description": "Enables the mage to hear whispers of past events that occurred in their current location, revealing secrets and hidden truths." },
        { "name": "Basic Combat Skills", "description": "Access to basic combat maneuvers like Power Strike (a strong, single-target attack) and Quick Jab (a fast, low-damage attack with a chance to stun)." },
        { "name": "Basic Metalworking", "description": "Gain proficiency in basic forging techniques, allowing the creation of simple tools and weapons (e.g., daggers, hammers, basic swords) with a +1 bonus to crafting rolls." },
        { "name": "Battlefield Control", "description": "Use your knowledge of the environment to control the battlefield, setting traps, and creating advantageous positions for your party." },
        { "name": "Blazing Leap", "description": "Boosts the mage's jump with a burst of fire from the feet, allowing them to leap great distances or over obstacles." },
        { "name": "Bloom Burst", "description": "Enables the mage to make a single plant bloom instantly or speed up the growth of a small patch of vegetation." },
        { "name": "Bone Craft", "description": "Manipulates small bones to form tools, keys, or weapons, providing the necromancer with versatile and often macabre equipment." },
        { "name": "Brigand’s Strike", "description": "When using a longsword or greatsword, you can perform a powerful strike to deal an extra 1d6 damage and cause the target to bleed. Roll your attack as usual; if it hits, roll an additional 1d6 for extra damage. The target must then succeed on a Constitution saving throw (DC 12) or take 1d4 bleeding damage at the start of their next turn." },
        { "name": "Breath of Comfort", "description": "Chills or warms the air around the caster or a small area, making it more comfortable in adverse weather conditions." },
        { "name": "Cleansing Wave", "description": "Releases a wave of water that washes over an area, removing dirt, toxins, and minor enchantments." },
        { "name": "Clay Harden", "description": "Hardens mud or clay into a durable ceramic-like material, ideal for creating temporary shelters or barriers." },
        { "name": "Commander’s Strike", "description": "Lead by example with a devastating strike using a longsword or greatsword. Roll your attack as usual; if it hits, roll an additional 2d6 for extra damage. Allies within 10 feet gain a +1 bonus to their next attack roll." },
        { "name": "Comet Trail", "description": "Allows the caster to leave behind a faint trail of shimmering light that only they can see, useful for marking paths or retracing steps." },
        { "name": "Combat Evasion", "description": "Dodge incoming attacks more effectively, giving you a temporary bonus to evasion during combat." },
        { "name": "Cosmic Awareness", "description": "Expands the caster's senses, allowing them to detect magic and celestial energies at great distances, or through barriers." },
        { "name": "Current Control", "description": "Manipulates existing bodies of water to create currents strong enough to transport objects or people, or to hinder enemy movements." },
        { "name": "Dagger", "description": "A melee or ranged weapon attack with a dagger." },
        { "name": "Dagger Attack", "description": "A melee or ranged weapon attack with a dagger." },
        { "name": "Death Throes", "description": "When the creature dies, it explodes, dealing damage to nearby creatures." },
        { "name": "Dew Touch", "description": "A gentle spell that causes a light dew to settle on objects, useful for aiding plant growth or cleaning surfaces." },
        { "name": "Divine Awareness", "description": "The creature knows if it hears a lie." },
        { "name": "Divine Smite", "description": "Channel divine energy into an attack, dealing radiant damage to an enemy. Useful for combating undead and dark creatures. " },
        { "name": "Earth Meld", "description": "Allows the mage to merge temporarily with the earth, becoming invisible and undetectable while within the soil." },
        { "name": "Elite Caravan", "description": "Increase your caravan guard to up to 20 members with higher morale and advanced combat skills, ensuring better protection and efficiency on trade routes." },
        { "name": "Feather Fall", "description": "Slows the descent of the caster or an object, allowing them to fall gently like a feather to the ground." },
        { "name": "Field Repair", "description": "Perform quick, effective repairs on advanced machinery and magical devices, restoring them to full functionality in the field." },
        { "name": "Fire Aura", "description": "Deals fire damage to creatures within a certain range at the start of each of its turns." },
        { "name": "Fire Cloak", "description": "Wraps the caster in flames that do not harm them but deal 1d6 + STR mod fire damage per turn to any who come too close, offering protection and a melee deterrent." },
        { "name": "Firebind", "description": "Encircles a target with a ring of fire, immobilizing them and dealing 1d6 + STR mod fire damage per round if they attempt to cross the flame barrier." },
        { "name": "Flameheart", "description": "Temporarily increases the caster’s resistance to physical damage, converting a portion of any damage taken into health regeneration via the heat of battle." },
        { "name": "Flying Sword", "description": "The creature's sword hovers and attacks on its command." },
        { "name": "Form Caravan", "description": "Form a small caravan guard of up to 5 members with basic morale and skills to protect your goods on trade routes." },
        { "name": "Galloping Strike", "description": "Perform a devastating galloping strike with a longsword or greatsword. Roll your attack as usual; if it hits, deal an additional 4d6 damage and cause fear in nearby enemies (Wisdom saving throw, DC 15)." },
        { "name": "Gadget Creation", "description": "Craft small, useful gadgets such as a mechanical flashlight, grappling hook, or basic alarm system. Provides a +1 bonus to crafting checks." },
        { "name": "Greatsword", "description": "A melee weapon attack with a greatsword, dealing extra radiant damage." },
        { "name": "Greataxe", "description": "A melee weapon attack with a greataxe." },
        { "name": "Heroic Charge", "description": "Perform a heroic charge with your lance, dealing massive damage. Roll your attack as usual; if it hits, deal an additional 3d6 damage and knock the target prone (Strength saving throw, DC 15)." },
        { "name": "Heroic Stand", "description": "Make a last stand in combat, greatly increasing your abilities and providing significant boosts to your party's defense and morale." },
        { "name": "Hooves", "description": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) bludgeoning damage." },
        { "name": "Impenetrable Defense", "description": "Ability to adopt a defensive stance that greatly reduces incoming physical damage." },
        { "name": "Ink Cloud", "description": "Releases a cloud of ink underwater, obscuring the area and allowing for a bonus action." },
        { "name": "Innovation Hub", "description": "Establish a portable workshop that allows for on-the-spot crafting and repairs, significantly speeding up the creation process and improving quality." },
        { "name": "Intermediate Metalworking", "description": "Gain proficiency in handling more complex projects and materials, including alloys and higher-quality metals, with a +2 bonus to crafting rolls." },
        { "name": "Lance Charge", "description": "Perform a powerful charge attack with a lance. Roll your attack as usual; if it hits, deal an additional 2d6 damage and potentially knock the target prone (Strength saving throw, DC 12)." },
        { "name": "Longsword", "description": "A melee weapon attack with a longsword, dealing extra damage on a critical hit." },
        { "name": "Longsword Attack", "description": "A melee weapon attack with a longsword." },
        { "name": "Magic Weapons", "description": "The creature's weapon attacks are magical." },
        { "name": "Mechanical Familiar", "description": "Build a small mechanical companion that can assist in tasks, provide surveillance, or deliver messages." },
        { "name": "Mechanical Guardian", "description": "Construct a large mechanical guardian to protect you and your allies, capable of engaging in combat and defending against threats." },
        { "name": "Moisture Conjuration", "description": "Allows the mage to extract moisture from the air to hydrate themselves or others, or to fill a small container with water." },
        { "name": "Multiattack", "description": "The creature makes multiple attacks in one turn." },
        { "name": "Noble’s Honor", "description": "Perform an honorable duel with a rapier or greatsword. Roll your attack as usual; if it hits, roll an additional 3d6 for extra damage and reduce the target's AC by 2 until the end of your next turn." },
        { "name": "Pathfinder's Rally", "description": "Boost your party's morale and combat effectiveness, increasing attack speed, damage, and defense for a short period." },
        { "name": "Phoenix Dive", "description": "Transforms the caster briefly into a fiery phoenix, capable of flying short distances and exploding into flames upon touchdown." },
        { "name": "Polearm Mastery", "description": "Gain increased proficiency with two-handed polearms, allowing for sweeping attacks that can hit multiple enemies. Roll your attack as usual; on a hit, you can target another enemy within 5 feet of the original target with the same roll." },
        { "name": "Quick Fix", "description": "Temporarily repair a broken item or device, restoring its functionality for a limited time." },
        { "name": "Quick Hide", "description": "Quickly hide yourself and your party from sight, useful for avoiding encounters or ambushes." },
        { "name": "Quick Shot", "description": "Use a bow or crossbow to make a rapid, accurate shot at an enemy, dealing extra damage. Deals 1d8 + DEX mod piercing damage." },
        { "name": "Rapid Camp Setup", "description": "Set up a secure campsite quickly, reducing the time needed for rest and recovery. Grants temporary bonuses to health and stamina recovery for your party." },
        { "name": "Rallying Cry", "description": "Inspire your troops with a rallying cry, restoring their morale and health. Allies within 30 feet regain 2d6 HP and gain advantage on their next attack roll." },
        { "name": "Reckless", "description": "The creature gains advantage on its melee weapon attack rolls, but attack rolls against it also have advantage." },
        { "name": "Reckless Charge", "description": "When using a two-handed polearm, charge at an enemy within 20 feet. Roll your attack as usual; if it hits, the target is knocked back 10 feet and takes an additional 1d8 damage." },
        { "name": "Reinforced Caravan", "description": "Expand your caravan guard to up to 10 members, improving their morale and skills, making them more effective in protecting your trade routes." },
        { "name": "Root Bridge", "description": "Manipulates tree roots or large vines to create a natural bridge or ladder, which can be used for crossing gaps or climbing." },
        { "name": "Royal Caravan", "description": "Command a caravan guard of up to 80 members with exceptional morale and legendary combat skills, providing unmatched security and efficiency for your trade operations." },
        { "name": "Scout Ahead", "description": "Scout ahead of your party to detect dangers, traps, or hidden treasures, and provide a detailed report on what lies ahead." },
        { "name": "Scimitar", "description": "A melee weapon attack with a scimitar." },
        { "name": "Shield Bash", "description": "A melee weapon attack with a shield, potentially knocking the target prone." },
        { "name": "Shield Block", "description": "Ability to use shields effectively to block attacks, reducing incoming damage by 2 points and increasing AC by +2." },
        { "name": "Silent Takedown", "description": "Eliminate an enemy silently, preventing them from alerting others." },
        { "name": "Silent Steps", "description": "Muffles the sound of movement, enabling the caster or a designated person to move silently for a short period." },
        { "name": "Spear", "description": "A melee or ranged weapon attack with a spear, dealing extra damage when used with two hands." },
        { "name": "Spirit Flicker", "description": "Briefly reveals the spirits in the vicinity, showing ghosts or remnants of the dead that can provide clues or warnings." },
        { "name": "Squad Command", "description": "Issue commands to allies that grant them bonuses in combat, increasing their Level 1-2 attacks by +1." },
        { "name": "Stellar Intuition", "description": "Grants the mage the ability to receive vague but useful hints about an opponent's next three actions, enhancing tactical decisions." },
        { "name": "Stone Smooth", "description": "Smoothens rough stones or pebbles in a small area, useful for crafting or creating safe walking paths." },
        { "name": "Swift Flanking", "description": "Lead a rapid flanking maneuver, allowing your cavalry to attack enemies from the sides. Provides a +2 bonus to attack rolls when flanking." },
        { "name": "Tactical Retreat", "description": "Ability to execute a strategic withdrawal, allowing the mercenary and their allies to disengage from combat without provoking attacks of opportunity." },
        { "name": "Teleport", "description": "The creature magically teleports to an unoccupied space it can see." },
        { "name": "Tentacles", "description": "A melee weapon attack with tentacles, potentially grappling the target." },
        { "name": "Trailblazer", "description": "Clear a path through difficult terrain, reducing travel time and avoiding natural hazards for your party." },
        { "name": "Trampling Charge", "description": "If the horse moves at least 20 ft. straight toward a creature and then hits it with a hooves attack on the same turn, that target must succeed on a DC 14 Strength saving throw or be knocked prone. If the target is prone, the horse can make another attack with its hooves against it as a bonus action." },
        { "name": "Veteran Caravan", "description": "Expand your caravan guard to up to 40 members with superior morale and elite combat skills, making them formidable protectors of your trade interests." },
        { "name": "Veteran’s Fury", "description": "When using a longsword or greatsword, unleash a flurry of attacks. Roll three separate attack rolls; each hit deals normal damage. On a critical hit, deal an additional 2d6 damage." },
        { "name": "Voice of Authority", "description": "The caster’s voice commands attention and obedience from those who hear it, influencing their actions subtly." },
        { "name": "Voice Throw", "description": "Allows the mage to project their voice to a specific location within sight, making it appear as if the voice is coming from somewhere else." },
        { "name": "War Cry", "description": "Emit a powerful shout that boosts the morale of allies, increasing their attack and defense stats by +4." },
        { "name": "Warrior’s Wrath", "description": "Channel your fury into a two-handed polearm, delivering a powerful, ground-shaking strike. Roll your attack as usual; if it hits, all enemies within 10 feet of the target must make a Dexterity saving throw (DC 15) or be knocked prone and take 2d8 damage." },
        { "name": "Water Breathing", "description": "Grants the caster or a chosen individual the ability to breathe underwater for a limited time." },
        { "name": "Whip", "description": "A melee weapon attack with a whip, with additional effects on a successful hit." },
        { "name": "Whispering Breeze", "description": "Creates a gentle gust of wind that can carry a soft message to someone nearby, subtly without drawing attention." },
        { "name": "Wind Shield", "description": "Creates a barrier of swirling wind around the caster, deflecting small projectiles and dispersing fog or smoke." }

    ],
    "reactions": [
        { "name": "Parry", "description": "The creature adds 2 to its AC against one melee attack that would hit it, provided it can see the attacker and is wielding a melee weapon." },
        { "name": "Skilled Parry", "description": "The creature adds 4 to its AC against one melee attack that would hit it, provided it can see the attacker and is wielding a melee weapon." }
    ],
    "abilities": [
        { "name": "Advanced Bargaining", "description": "Gain a +2 bonus to all trade and negotiation checks, enhancing your ability to secure favorable deals." },
        { "name": "Advanced Weapon Mastery", "description": "Gain proficiency with a broader array of weapons (axes, maces, crossbows) and a +2 bonus to attack rolls with all weapons." },
        { "name": "Battlefield Command", "description": "Issue commands to your militia to improve their coordination and effectiveness. Allies within 30 feet gain a +1 bonus to attack rolls and saving throws." },
        { "name": "Basic Cure", "description": "Cure common ailments and minor diseases, ensuring your party remains healthy during their travels" },
        { "name": "Blazing Leap", "description": "Boosts the mage's jump with a burst of fire from the feet, allowing them to leap great distances or over obstacles." },
        { "name": "Bone Craft", "description": "Manipulates small bones to form tools, keys, or weapons, providing the necromancer with versatile and often macabre equipment." },
        { "name": "Brave", "description": "The creature has advantage on saving throws against being frightened." },
        { "name": "Brute", "description": "A melee weapon deals one extra die of its damage when the creature hits with it (included in the attack)." },
        { "name": "Captain’s Command", "description": "Issue commands to your cavalry to execute complex maneuvers, providing a +2 bonus to attack and defense rolls for the unit." },
        { "name": "Cavalry Formation", "description": "Lead your unit in a basic cavalry formation, improving their charge effectiveness and providing a +1 bonus to attack rolls when charging." },
        { "name": "Cultural Insight", "description": "Use your knowledge of local cultures to gain favor or negotiate better deals, providing temporary boosts to diplomacy and trade interactions." },
        { "name": "Defensive Stance", "description": "Adopt a defensive stance with a longsword or greatsword. On your turn, instead of attacking, gain +2 AC until the start of your next turn." },
        { "name": "Disciplined Attack", "description": "When using a rapier, perform a precise attack. Roll your attack as usual; if it hits, roll an additional 1d6 for critical hit chance. On a critical hit, deal an extra 2d6 damage." },
        { "name": "Earth Meld", "description": "Allows the mage to merge temporarily with the earth, becoming invisible and undetectable while within the soil." },
        { "name": "Economic Influence", "description": "Gain a +4 bonus to all trade, negotiation, and market manipulation checks, allowing you to control market trends to some extent." },
        { "name": "Enhanced Cavalry Formation", "description": "Lead your unit in an advanced cavalry formation, significantly improving their charge effectiveness and providing a +2 bonus to attack rolls when charging." },
        { "name": "Enhanced Durability", "description": "Items crafted have increased durability, reducing the frequency of necessary repairs and improving overall longevity." },
        { "name": "Enhanced Evasion", "description": "Dodge incoming attacks with increased effectiveness, making you harder to hit in combat." },
        { "name": "Feather Fall", "description": "Slows the descent of the caster or an object, allowing them to fall gently like a feather to the ground." },
        { "name": "Flameheart", "description": "Temporarily increases the caster’s resistance to physical damage, converting a portion of any damage taken into health regeneration via the heat of battle." },
        { "name": "Grove Sentinel", "description": "Animates a tree to serve as a temporary guardian, giving it limited movement and the ability to attack intruders, dealing 2d6 + INT mod bludgeoning damage." },
        { "name": "Haggle", "description": "Improve your negotiation skills, giving you a +1 bonus to all negotiation and persuasion checks." },
        { "name": "Hold Breath", "description": "While out of water, the creature can hold its breath for 1 hour." },
        { "name": "Lord’s Command", "description": "Issue strategic commands that coordinate large-scale cavalry maneuvers, providing a +3 bonus to attack and defense rolls for the unit." },
        { "name": "Market Manipulation", "description": "Gain a +3 bonus to all trade and market analysis checks, allowing you to predict and influence market trends." },
        { "name": "Market Savvy", "description": "Gain a +1 bonus to all trade and market analysis checks, allowing you to buy low and sell high more effectively." },
        { "name": "Master Tracker", "description": "Track any creature or human with unparalleled precision, even through the most challenging environments." },
        { "name": "Master of Markets", "description": "Gain a +5 bonus to all trade, negotiation, and market manipulation checks, allowing you to dominate regional and international markets." },
        { "name": "Network Expansion", "description": "Establish a wider network of contacts, providing access to rare items and exclusive deals." },
        { "name": "Recruit Elite Cavalry", "description": "Expand your cavalry unit to up to 50 members, providing them with advanced combat and riding training, significantly boosting their morale." },
        { "name": "Recruit Even More Peasants", "description": "Expand your militia to up to 50 members, providing them with advanced combat training and significantly boosting their morale." },
        { "name": "Recruit Legendary Cavalry", "description": "Command a large cavalry unit of up to 100 members, turning them into a highly skilled and motivated force." },
        { "name": "Recruit Maximum Peasants", "description": "Command a large militia of up to 100 members, turning them into a highly skilled and motivated force." },
        { "name": "Recruit More Cavalry", "description": "Increase your cavalry unit to up to 25 members, enhancing their riding skills and morale." },
        { "name": "Recruit More Peasants", "description": "Increase your militia to up to 25 members, enhancing their combat skills and morale." },
        { "name": "Recruit Peasants", "description": "Recruit up to 10 peasants to form a basic militia, improving their morale and providing basic combat training." },
        { "name": "Recruit Peasants as Cavalry", "description": "Recruit up to 10 peasants to form a basic cavalry unit, improving their morale and providing basic riding and combat training." },
        { "name": "Renowned Reputation", "description": "A legendary status that draws clients from all over Elyndor, ensuring high demand and top-tier compensation for their work." },
        { "name": "Riding Mastery", "description": "Gain proficiency in advanced riding techniques, including high-speed maneuvers and jumps. Provides a +1 bonus to all riding checks." },
        { "name": "Scout’s Eye", "description": "Use your mobility to scout ahead and gather intelligence. Provides a +1 bonus to perception and survival checks while mounted." },
        { "name": "Shield Wall", "description": "Coordinate with your militia to form a defensive shield wall. All members gain +2 AC while in formation." },
        { "name": "Signature Creations", "description": "Develop unique crafting techniques that grant items special attributes or abilities (e.g., increased critical hit chance, enhanced resistance to elements)." },
        { "name": "Specialization", "description": "Choose a type of goods (luxuries, artifacts, essentials) and gain a +2 bonus to all trades involving those goods." },
        { "name": "Stealth Mode", "description": "Move silently and remain undetected by enemies, allowing you to bypass guards or set up ambushes." },
        { "name": "Supreme Cavalry Formation", "description": "Lead your unit in a supreme cavalry formation, providing unparalleled charge effectiveness and a +3 bonus to attack rolls when charging." },
        { "name": "Supreme Command", "description": "Lead your troops with unparalleled tactical acumen. Allies within 60 feet gain a +2 bonus to attack rolls, damage rolls, and saving throws." },
        { "name": "Survival Instinct", "description": "Boost your survival skills temporarily to forage for food or find water, providing immediate resources for your party." },
        { "name": "Terrain Navigation", "description": "Navigate through difficult terrains such as dense forests, swamps, and mountains with ease." },
        { "name": "Toughened Body", "description": "Passive ability that increases overall health and reduces fatigue, providing a flat increase to HP of +5 and resistance to physical status effects." },
        { "name": "Track", "description": "Follow the trails of creatures or humans, identifying their movements and behaviors." },
        { "name": "Trade Routes", "description": "Establish reliable and profitable trade routes, reducing the risk of bandit attacks and increasing your profit margins." },
        { "name": "Ultimate Repair", "description": "Instantly repair any damaged device or construct to full functionality, regardless of its complexity or the extent of the damage." },
        { "name": "Underwater Camouflage", "description": "The creature has advantage on Dexterity (Stealth) checks made while underwater." },
        { "name": "Water Breathing", "description": "The creature can breathe only underwater." },
        { "name": "Water Breathing", "description": "Grants the caster or a chosen individual the ability to breathe underwater for a limited time." },
        { "name": "Waterform Shield", "description": "Creates a large, protective barrier of swirling water around the caster, which can absorb and dissipate energy from magical and physical attacks." },
        { "name": "Weapon Training", "description": "Gain proficiency with common weapons (swords, spears, bows) and a +1 bonus to attack rolls with these weapons." },
        { "name": "Wind Shield", "description": "Creates a barrier of swirling wind around the caster, deflecting small projectiles and dispersing fog or smoke." }
      
    ],
    "items": [
        { "name": "Sword", "description": "A sharp blade", "weight": 5 },
        { "name": "Shield", "description": "Provides protection", "weight": 10 },
        { "name": "Potion", "description": "Heals 50 health points", "weight": 1 },
        { "name": "Club", "description": "Swings within 5 ft for 1d4+STR mod damage. Light weapon, can be used as a secondary weapon in dual wielding.", "weight": 2 },
        { "name": "Dagger", "description": "Stabs or slashes within 5 ft for 1d4+STR mod damage. Can be used as a finesse weapon with DEX instead of STR. Can also be thrown up to 60 ft for the same damage.", "weight": 1 },
        { "name": "Greatclub", "description": "Swings to strike within 5 ft for 1d8+STR mod damage. Two-handed use required.", "weight": 10 },
        { "name": "Handaxe", "description": "Chops within 5 ft for 1d6+STR mod damage. Can also be thrown up to 60 ft for the same damage.", "weight": 2 },
        { "name": "Light Hammer", "description": "Strikes within 5 ft for 1d4+STR mod damage. Can be thrown up to 60 ft for the same damage. Light weapon, can be used for dual wielding.", "weight": 2 },
        { "name": "Javelin", "description": "Thrusts or throws within 5 ft for 1d6+STR mod damage. Can be thrown up to 120 ft for the same damage.", "weight": 2 },
        { "name": "Mace", "description": "Bashes within 5 ft for 1d6+STR mod damage.", "weight": 4 },
        { "name": "Quarterstaff", "description": "Strikes within 5 ft for 1d6+STR mod damage. Versatile, can be used with two hands for 1d8+STR mod damage.", "weight": 4 },
        { "name": "Sickle", "description": "Slices within 5 ft for 1d4+STR mod damage. Light weapon, can be used for dual wielding.", "weight": 2 },
        { "name": "Spear", "description": "Thrusts within 5 ft for 1d6+STR mod damage. Can be thrown up to 60 ft for the same damage. Versatile, can be used with two hands for 1d8+STR mod damage.", "weight": 3 },
        { "name": "Light Crossbow", "description": "Shoots a bolt up to 80 ft for 1d8+DEX mod damage, or up to 320 ft with disadvantage. Must be loaded as part of the attack.", "weight": 5 },
        { "name": "Dart", "description": "Throws within 30 ft for 1d4+DEX mod damage, or up to 120 ft with disadvantage. Uses finesse, applying DEX instead of STR for attack rolls.", "weight": 0.25 },
        { "name": "Shortbow", "description": "Shoots an arrow up to 80 ft for 1d6+DEX mod damage, or up to 320 ft with disadvantage. Must be used with arrows.", "weight": 2 },
        { "name": "Sling", "description": "Flings a bullet up to 30 ft for 1d4+DEX mod damage, or up to 120 ft with disadvantage. Uses ammunition - sling bullets.", "weight": 0 },
        { "name": "Blowgun", "description": "Fires needles up to 25 ft for 1 piercing damage, or up to 100 ft with disadvantage. Must be used with blowgun needles.", "weight": 1 },
        { "name": "Crossbow Bolts", "description": "Ammunition for a crossbow, can be used with either a hand, light, or heavy crossbow.", "weight": 1 },
        { "name": "Arrows", "description": "Ammunition for a bow, must be used with either a shortbow or a longbow.", "weight": 1 },
        { "name": "Longsword", "description": "Swings or thrusts to attack within 5 ft for 1d8+STR mod damage. If used with both hands, damage increases to 1d10+STR mod.", "weight": 3 },
        { "name": "Lance", "description": "Thrusts to attack from horseback with reach up to 10 ft for 1d12+STR mod damage. Disadvantage on attacks against targets within 5 ft.", "weight": 6 },
        { "name": "Maul", "description": "Swings to strike with heavy impact within 5 ft for 2d6+STR mod damage. Disadvantage on small creatures.", "weight": 10 },
        { "name": "Morningstar", "description": "Strikes within 5 ft for 1d8+STR mod damage.", "weight": 4 },
        { "name": "Pike", "description": "Thrusts to attack with reach up to 10 ft for 1d10+STR mod damage. Two-handed use only.", "weight": 18 },
        { "name": "Rapier", "description": "Thrusts or slices within 5 ft for 1d8+DEX mod damage, using finesse to leverage DEX instead of STR for attack rolls.", "weight": 2 },
        { "name": "Battleaxe", "description": "Chops or hacks within 5 ft for 1d8+STR mod damage. When used with two hands, damage increases to 1d10+STR mod.", "weight": 4 },
        { "name": "Flail", "description": "Swings to attack within 5 ft for 1d8+STR mod damage.", "weight": 2 },
        { "name": "Glaive", "description": "Slices with a long blade on a pole, attacking with reach up to 10 ft for 1d10+STR mod damage. Disadvantage on attacks against targets within 5 ft.", "weight": 6 },
        { "name": "Greataxe", "description": "Cleaves with a massive axe within 5 ft for 1d12+STR mod damage.", "weight": 7 },
        { "name": "Halberd", "description": "Slices or hooks with reach up to 10 ft for 1d10+STR mod damage.", "weight": 6 },
        { "name": "Scimitar", "description": "Slices within 5 ft for 1d6+DEX mod damage, using finesse to apply DEX instead of STR for attack rolls.", "weight": 3 },
        { "name": "Shortsword", "description": "Stabs or cuts within 5 ft for 1d6+DEX mod damage, using finesse to apply DEX instead of STR for attack rolls.", "weight": 2 },
        { "name": "Trident", "description": "Thrusts or throws within 5 ft for 1d6+STR mod damage, or throws up to 20 ft for the same damage. Versatile to use with both hands for 1d8+STR mod damage.", "weight": 4 },
        { "name": "War Pick", "description": "Pierces armor within 5 ft for 1d8+STR mod damage.", "weight": 2 },
        { "name": "Warhammer", "description": "Smashes within 5 ft for 1d8+STR mod damage. When used with two hands, damage increases to 1d10+STR mod.", "weight": 2 },
        { "name": "Longbow", "description": "Shoots an arrow from a quiver up to 150 ft for 1d8+DEX mod damage, or up to 600 ft with disadvantage.", "weight": 2 },
        { "name": "Blowgun", "description": "Fires a dart up to 25 ft for 1 piercing damage, or up to 100 ft with disadvantage.", "weight": 1 },
        { "name": "Crossbow, Hand", "description": "Shoots a bolt up to 30 ft for 1d6+DEX mod damage, or up to 120 ft with disadvantage.", "weight": 3 },
        { "name": "Crossbow, Heavy", "description": "Shoots a bolt up to 100 ft for 1d10+DEX mod damage, or up to 400 ft with disadvantage.", "weight": 18 },
        { "name": "Sling Bullets", "description": "Ammunition for a sling, must be used with a sling.", "weight": 1 }

    ],
    "classes": [
        { "name": "Warrior" },
        { "name": "Acolyte Mage" },
        { "name": "Blue Mage" },
        { "name": "Red Mage" },
        { "name": "Green Mage" },
        { "name": "Golden Mage" },
        { "name": "Void Sorcerer" },
        { "name": "Necromancer" },
        { "name": "Light Magicka" },
        { "name": "Cosmic Sorcerer" },
        { "name": "Blacksmith" },
        { "name": "Horseman" },
        { "name": "Mercenary" },
        { "name": "Wanderer" },
        { "name": "Inventor" },
        { "name": "Merchant" },
        { "name": "Cleric" },
        { "name": "Animal" },
        { "name": "Rogue/Ranger" }

    ],
    "races": [
        {
            "name": "Human",
            "modifiers": {
                "STR": 0,
                "DEX": 0,
                "CON": 0,
                "INT": 0,
                "CHA": 0,
                "STA": 0,
                "PER": 0
            }
        },
        {
            "name": "Elf",
            "modifiers": {
                "STR": -1,
                "DEX": 2,
                "CON": -1,
                "INT": 1,
                "CHA": 1,
                "STA": -1,
                "PER": 2
            }
        },
        {
            "name": "Dwarf",
            "modifiers": {
                "STR": 1,
                "DEX": -1,
                "CON": 2,
                "INT": 0,
                "CHA": -1,
                "STA": 2,
                "PER": 0
            }
        },
        {
            "name": "Orc",
            "modifiers": {
                "STR": 2,
                "DEX": 0,
                "CON": 2,
                "INT": -1,
                "CHA": -1,
                "STA": 1,
                "PER": -1
            }
        },
        {
            "name": "Halfling",
            "modifiers": {
                "STR": -1,
                "DEX": 2,
                "CON": 0,
                "INT": 0,
                "CHA": 1,
                "STA": 0,
                "PER": 1
            }
        }
    ]
};
